# Generated by Django 6.0.7 on 2026-07-30 08:10

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefaultRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("insite", "In-site")],
                        max_length=16,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ("channel", "address"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel", "address"), name="notifier_uniq_default_recipient"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(
                        help_text="Logical lookup key, e.g. order-shipped. Shared across channels.",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("insite", "In-site")],
                        max_length=16,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body_text", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("key", "channel"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "channel"), name="notifier_uniq_template_key_channel"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("insite", "In-site")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "group_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Shared by the sibling rows of one multi-channel send.",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='What caused this send, e.g. "order.shipped", "cron:daily-digest".',
                        max_length=100,
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body_text", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), blank=True, default=list
                    ),
                ),
                (
                    "read_by",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), blank=True, default=list
                    ),
                ),
                ("rendered_subject", models.CharField(blank=True, max_length=255)),
                ("rendered_text", models.TextField(blank=True)),
                ("rendered_html", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("send_attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notifier.notificationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("suppressed", "Suppressed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=16,
                    ),
                ),
                ("backend", models.CharField(blank=True, max_length=255)),
                (
                    "requested_recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), blank=True, default=list
                    ),
                ),
                (
                    "effective_recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), blank=True, default=list
                    ),
                ),
                ("env", models.CharField(blank=True, max_length=32)),
                ("is_async", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="notifier.notification",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["notification", "created_at"], name="notifier_log_notif_created"
                    ),
                    models.Index(
                        fields=["result", "-created_at"], name="notifier_log_result_created"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["status", "channel"], name="notifier_status_channel"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["channel", "status", "-created_at"], name="notifier_chan_stat_created"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["recipients"], name="notifier_recipients_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("channel", "sms"), _negated=True),
                    models.Q(("body_html", ""), ("rendered_html", "")),
                    _connector="OR",
                ),
                name="notifier_sms_has_no_html",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(("channel", "insite"), ("read_by", []), _connector="OR"),
                name="notifier_read_by_insite_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "sent"), _negated=True),
                    ("sent_at__isnull", False),
                    _connector="OR",
                ),
                name="notifier_sent_requires_sent_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(("recipients__len__lte", 500)), name="notifier_max_recipients"
            ),
        ),
    ]
